from pathlib import Path
p = Path('/home/ubuntu/aula-ia-cientifica/client/src/pages/Admin.tsx')
s = p.read_text()
s = s.replace('Panel privado del investigador', 'Vista del profesor · Resultados')
s = s.replace('Investigación educativa · V2', 'Vista del profesor · Resultados del programa')
s = s.replace('Seguimiento individual y análisis agregado sin exponer resultados al estudiante.', 'Tablero de resultados, rendimiento y comparación PRETEST/POSTEST. Esta información solo está disponible para el encargado del programa.')
s = s.replace('const data = research.data; const summary', 'const data = research.data; const institutions = Array.from(new Set((data?.students ?? []).map(student => student.school))); const summary')
marker = '<section className="mt-6 rounded-2xl bg-white p-6 shadow-soft"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center">'
insert = '''<section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-2xl bg-white p-6 shadow-soft"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold text-[#26356b]">Rendimiento por módulo</h2><p className="mt-1 text-sm text-[#789093]">Promedio de avance registrado por tema.</p></div><BarChart3 className="text-[#5b4bdb]" /></div><div className="mt-6 space-y-4">{(data?.moduleUsage ?? []).map(module => <div key={module.moduleId}><div className="mb-1 flex justify-between text-sm font-bold text-[#547074]"><span>{module.moduleId.toUpperCase()}</span><span>{module.average}% · {module.users} estudiante(s)</span></div><div className="h-3 overflow-hidden rounded-full bg-[#e8eaf8]"><div className="h-full rounded-full bg-[#5b4bdb]" style={{ width: `${module.average}%` }} /></div></div>)}{!(data?.moduleUsage?.length) && <p className="py-6 text-sm text-[#789093]">Los datos aparecerán cuando los estudiantes completen módulos.</p>}</div></div><div className="rounded-2xl bg-white p-6 shadow-soft"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold text-[#26356b]">Resultados por institución</h2><p className="mt-1 text-sm text-[#789093]">Lectura rápida para acompañamiento docente.</p></div><School className="text-[#e27a4f]" /></div><div className="mt-6 space-y-3">{institutions.map(institution => { const institutionRows = (data?.students ?? []).filter(student => student.school === institution); const scores = institutionRows.filter(student => student.pretest !== null).map(student => student.pretest as number); const average = scores.length ? Math.round(scores.reduce((sum, value) => sum + value, 0) / scores.length) : 0; return <div key={institution} className="rounded-xl bg-[#f7f8ff] p-4"><div className="flex items-center justify-between"><span className="font-bold text-[#26356b]">{institution}</span><span className="text-sm font-bold text-[#5b4bdb]">{average}%</span></div><p className="mt-1 text-xs text-[#789093]">{institutionRows.length} estudiante(s) · {scores.length} pretest(s)</p></div>; })}{!institutions.length && <p className="py-6 text-sm text-[#789093]">Las instituciones aparecerán al registrar estudiantes.</p>}</div></div></section>'''
if marker in s:
    s = s.replace(marker, insert + marker, 1)
p.write_text(s)
print('Teacher view enhanced.')
